### ISSUE TITLE
Add support for Linux 4.19 (UDM firmware 1.10.0)

### ISSUE THREAD

**Issue by TheJulianJES** [fabianishere/udm-kernel-tools#6]
UniFi Dream Machine Firmware 1.10.0-8 (Beta) firmware upgraded the kernel to 4.19.
Since the kernel doesn't seem to have been upgraded in a long time, I guess the maintenance guide (https://github.com/fabianishere/udm-kernel-tools/blob/master/MAINTENANCE.md#adding-firmware-support) will not just work(?)

The project by @tusc (https://github.com/tusc/wireguard-kmod) already includes support for the new kernel (4.19.152), although it doesn't look like he posted the source he was sent by Ubiquiti (at https://github.com/tusc/UDM-source-code).
(Perhaps because the firmware is still in beta, Ubiquiti doesn't want him to, or he just hasn't gotten around to it?)

Even though it'll probably take some time until the firmware reaches RC or "stable", it might be a good idea to see what's needed to support a new kernel.

(Again, big thanks for both projects!)

**Comment by fabianishere** [comment]
Thanks for creating the issue. It is indeed important to support the new kernel before UDM/P firmware 1.10.0 is officially released.

When Ubiquiti moves to a Linux kernel for the UDM/P firmware, three things need to happen:
1. [kexec-mod](https://github.com/fabianishere/kexec-mod) must support this new version. This will be the most difficult tasks, since the kexec internals might have changed in the meantime. However, given that the new firmware moves to kernel 4.19, which supports kexec natively (if enabled of course), the migration is simplified a lot.
2. The stock sources at [udm-kernel](https://github.com/fabianishere/udm-kernel) need to be updated with the new kernel sources from Ubiquiti. Fortunately, I have those sources already, but have not had the time yet to rebase them on top of the current sources.
3. The regular process in the [Maintenance Guide](https://github.com/fabianishere/udm-kernel-tools/blob/master/MAINTENANCE.md#adding-firmware-support) to support the new firmware.

**Comment by tusc** [comment]
Like Fabian, I haven't gotten around to it. :)

Will probably this week.

**Comment by fabianishere** [comment]
Fixed with #14. I will create a release for `udm-kernel-tools` and a compatible 4.19 kernel  soon.

**Comment by TheJulianJES** [comment]
I know this is a udm-kernel issue now (still waiting on the latest kernel source) but I just wanted to mention that 1.10 is now officially out as a "rolling upgrade": https://community.ui.com/releases/UniFi-OS-Dream-Machines-1-10-0/c4559fe1-52dc-4a6d-8991-d469959d366e
